server:
  port: 9001
spring:
  application:
    name: gateway-zuul
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.101.188:3306/suty?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
  redis:
    host: 114.215.25.156
    port: 6379
mybatis:
  type-aliases-package: com.cloud.apimodel.entity,com.cloud.apimodel.param
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    cache-enabled: false
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

logging:
  level:
    com.cloud.apiservice.mapper : debug


