server:
  port: 8881
spring:
  application:
    name: manage-backend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.111.237.66:3306/paas?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.cloud.apimodel.entity
                        ,com.cloud.apimodel.param
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    cache-enabled: false
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

