server:
  port: 8881
spring:
  application:
    name: manage-backend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.111.237.66:3306/paas?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.cloud.apimodel.entity
                        ,com.cloud.apimodel.param
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    cache-enabled: false
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

logging:
  level:
    com.cloud.apiservice.mapper : debug
#配置eureka获取服务地址
#配置eureka获取服务地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  #配置Swagger相关信息
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号